### ISSUE TITLE
Adding ESGD variant using Lop instead of Rop

### ISSUE THREAD

**Issue by rodrigob** [lmjohns3/downhill#11]
Albeit the [paper describes ESGD via a R-operator](http://arxiv.org/abs/1502.04390), the [code provided](https://gist.github.com/ynd/f1ce7133a03ec54d6eb9) (see arxiv v2) uses an L-operator.

Turns out that Theano has a terrible support for R-operators (see [here](https://github.com/Theano/Theano/issues/305) and [here](https://github.com/Theano/Theano/issues/3457) ). Thus is would make sense for Downhill to provide an "Lop variant" of ESGD.

**Comment by lmjohns3** [comment]
I added two alternative methods for computing the Hv value and profiled them using the rosenbrock function. Surprisingly I found the Rop variant to perform the best, but I added a switch so you can use the others if you prefer. To use:

    opt = downhill.build('esgd', ...)
    opt.hv_method = 'lop'  # or 'grad'
    opt.minimize(...)
