### ISSUE TITLE
Adding constraints?

### ISSUE THREAD

**Issue by sergeyf** [lmjohns3/downhill#12]
Hello,

Thanks for the great package. How hard would it be to add basic element-wise constraints?

**Comment by lmjohns3** [comment]
Downhill leaves constraints up to the user. If you have constraints on parameter values you can implement those yourself in two ways:

1. Combine the hard (or inequality) constraints with your loss using lagrange multipliers. You can then set the lagrange parameters to very high values (to mimic hard constraints) or to other values depending on the problem.

2. Use the iterative optimization interface to manually constrain variables periodically during optimization. Suppose you have a loss ``loss`` that is formulated to compute an optimal value for ``param``, but ``param`` must be between 0 and 1. Then you could do something like:

    opt = downhill.build(algo='nag', loss=loss)
    for _ in opt.iterate(dataset):
        param.set_value(np.clip(param.get_value(), 0, 1))

Hopefully that will get you started!

**Comment by sergeyf** [comment]
Great, thanks!
