### ISSUE TITLE
Matrix factorization fails with TypeError

### ISSUE THREAD

**Issue by ahwillia** [lmjohns3/downhill#17]
I just installed this package via pip and am unable to get the simple example from the README to compile. I get the following error:

```
/Users/alex/anaconda/lib/python2.7/site-packages/theano/compile/pfunc.pyc in
rebuild_collect_shared(outputs, inputs, replace,
updates, rebuild_strict, copy_inputs_over, no_default_updates)
    215                        ' function to remove broadcastable dimensions.')
    216 
--> 217             raise TypeError(err_msg, err_sug)
    218         assert update_val.type == store_into.type
    219 

TypeError: ('An update must have the same type as the original shared variable
(shared_var=v_g1_ewma, shared_var.type=TensorType(float32, matrix), 
update_val=Elemwise{add,no_inplace}.0, update_val.type=TensorType(float64, matrix)).',
'If the  difference is related to the broadcast pattern, you can call the
tensor.unbroadcast(var,  axis_to_unbroadcast[, ...]) function to remove
broadcastable dimensions.')
```

My theano and downhill versions according to pip freeze are:

```
downhill==0.3.2
Theano==0.7.0
```

I'm sorry if this report is vague and missing details - just let me know what is needed. I am new to theano.

**Comment by lmjohns3** [comment]
Could you try running the example with THEANO_FLAGS=floatX=float32? (Alternatively store this content:

    [global]
    floatX = float32

in your `.theanorc` file.) See http://deeplearning.net/software/theano/library/config.html for info on configuring theano.

**Comment by ahwillia** [comment]
Got it, thanks a million. It might be helpful to put this into the example? Just in the interest of having less users like me creating noise for you. Thanks again -- really appreciate it!
