### ISSUE TITLE
Is the B_1 decay in Adam appropriate?

### ISSUE THREAD

**Issue by rpryzant** [lmjohns3/downhill#18]
This is more of a question than an "issue" per-se.

On each Adam update, you decay `beta1`:
```
        beta1 = self.beta1 * self.beta1_decay ** t_tm1
```
and explain this by saying you want to compute an EWMA of beta1 in the docs.

But I don't see this step in the Adam paper which you cite (https://arxiv.org/pdf/1412.6980.pdf). 

Is this step appropriate?

**Comment by lmjohns3** [comment]
Thanks for the report! It looked like there were actually a number of differences between the paper and my implementation, so I updated the code to more closely match the paper (I hope). I haven't run any of the tests, so this might need some tweaking ... but it should be better at any rate.
